#!/bin/sh
set -e
# Automatically added by dh_installinit
if [ "$1" = install ] || [ "$1" = upgrade ]; then
	if [ -e "/etc/init.d/freehold" ] && [ -L "/etc/init.d/freehold" ] \
	   && [ $(readlink -f "/etc/init.d/freehold") = /lib/init/upstart-job ]
	then
		rm -f "/etc/init.d/freehold"
	fi
fi
# End automatically added section
